# Generated by Django 3.1.1 on 2020-09-11 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('openfoodfats_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=150, unique=True)),
                ('nutriscore_product', models.CharField(max_length=1)),
                ('store_product', models.CharField(max_length=100)),
                ('picture', models.URLField()),
                ('url_site', models.URLField()),
                ('fat', models.CharField(blank=True, max_length=100, null=True)),
                ('saturated_fat', models.CharField(blank=True, max_length=100, null=True)),
                ('sugars', models.CharField(blank=True, max_length=100, null=True)),
                ('salt', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categories')),
            ],
            options={
                'verbose_name': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Attributs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribut_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attributs',
            },
        ),
    ]
