# Generated by Django 3.1.1 on 2020-09-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='openfoodfats_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
