# Generated by Django 3.0.7 on 2020-08-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200710_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributs',
            options={'verbose_name': 'Attributs'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='attributs',
            name='product_choice',
        ),
    ]
