# Generated by Django 3.0.7 on 2020-08-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200815_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'categorie'},
        ),
    ]
