# Generated by Django 3.0.7 on 2020-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200831_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fat',
            field=models.CharField(default='?', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='salt',
            field=models.CharField(default='?', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='saturated_fat',
            field=models.CharField(default='?', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='sugars',
            field=models.CharField(default='?', max_length=10),
        ),
    ]
