# Generated by Django 3.0.7 on 2020-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200903_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fat',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='salt',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='saturated_fat',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='sugars',
            field=models.CharField(default='?', max_length=100),
        ),
    ]
