# Generated by Django 3.0.7 on 2020-09-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200903_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='salt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='saturated_fat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sugars',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
