# Generated by Django 3.0.7 on 2020-06-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150, unique=True)),
                ('nutriscore_product', models.CharField(max_length=1, unique=True)),
                ('store_product', models.CharField(max_length=100, unique=True)),
                ('picture', models.URLField()),
                ('url_site', models.URLField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Categories')),
            ],
        ),
    ]
