# Generated by Django 3.0.7 on 2020-06-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='nutriscore_product',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='store_product',
            field=models.CharField(max_length=100),
        ),
    ]
