# Generated by Django 3.0.7 on 2020-07-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200630_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Attributs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_choice', models.CharField(max_length=150)),
                ('attribut_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Products')),
                ('name_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Persons')),
            ],
        ),
    ]
