# Generated by Django 3.0.7 on 2020-07-10 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_attributs_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributs',
            name='name_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
